// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD993s_hepP5gV9I_JPYuwNpJ70nZIdZQ',
    appId: '1:612948530650:web:777bf983d4d70fd8219ce3',
    messagingSenderId: '612948530650',
    projectId: 'vianthotapp',
    authDomain: 'vianthotapp.firebaseapp.com',
    storageBucket: 'vianthotapp.appspot.com',
    measurementId: 'G-M2XZY90YPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0gXen4UP1zf2y6jCQs0ti5vylhkJisVo',
    appId: '1:612948530650:android:96e01d9c2e7249dc219ce3',
    messagingSenderId: '612948530650',
    projectId: 'vianthotapp',
    storageBucket: 'vianthotapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtVM5nZl4-uIJZJ_Ji2_U-Syo2XKFGzTk',
    appId: '1:612948530650:ios:f0abee4e1d943215219ce3',
    messagingSenderId: '612948530650',
    projectId: 'vianthotapp',
    storageBucket: 'vianthotapp.appspot.com',
    iosClientId: '612948530650-pkq2j2s19mu9grv6b34287bu1dl6lfeu.apps.googleusercontent.com',
    iosBundleId: 'com.thotjohn.android',
  );
}
